// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8J10ONhIHtYFIl3fUe3VNcOGwBw14_mI',
    appId: '1:1051245747836:web:6b1d29153e1b1ca69473f9',
    messagingSenderId: '1051245747836',
    projectId: 'cryptopredictor-b97e8',
    authDomain: 'cryptopredictor-b97e8.firebaseapp.com',
    storageBucket: 'cryptopredictor-b97e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvqWcG9gSBgNZeH8QJ34z1HfMLZG22PU',
    appId: '1:1051245747836:android:ee1e6dee31ab64259473f9',
    messagingSenderId: '1051245747836',
    projectId: 'cryptopredictor-b97e8',
    storageBucket: 'cryptopredictor-b97e8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8J10ONhIHtYFIl3fUe3VNcOGwBw14_mI',
    appId: '1:1051245747836:web:f1879bf37e0d14fb9473f9',
    messagingSenderId: '1051245747836',
    projectId: 'cryptopredictor-b97e8',
    authDomain: 'cryptopredictor-b97e8.firebaseapp.com',
    storageBucket: 'cryptopredictor-b97e8.firebasestorage.app',
  );

}